version: '3.8'
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=db_idea
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5436:5432'

  # mysql:
  #   image: mysql:9.0
  #   container_name: mysql_db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: db_idea
  #     MYSQL_USER: user_idea
  #     MYSQL_PASSWORD: root
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - '3307:3306'
